### ISSUE TITLE
Implement ctx.createBiquadFilter

### ISSUE THREAD

**Issue by ben-eb** [sebpiq/node-web-audio-api#26]
Thanks for this lib. Would like to use it to test `createBiquadFilter()`, if it's possible. Let me know if you have any alternate testing strategies, if you can! :smiley:

**Comment by sebpiq** [comment]
Hi Ben,

BiquadFilter is not implemented yet ... I would try testing stuff in the browser, it might be possible with OfflineAudioContext, depending on what you want to do ...

**Comment by ben-eb** [comment]
I'm not doing anything with the Web Audio APIs right now so it's not worth it for me to be tracking this issue, thanks anyway. 😄

**Comment by sebpiq** [comment]
alright! You're welcome!
