### ISSUE TITLE
speaker dependency install fails

### ISSUE THREAD

**Issue by hughrawlinson** [sebpiq/node-web-audio-api#36]
speaker 0.0.x fails to install on my machine, which is running OS X 10.3. The current version of speaker does not fail to install, but tests do fail for the node-web-audio-api.

[Test log is here](https://gist.github.com/hughrawlinson/7576d3faa62da1ad6e0e).

I'll do my best to submit a PR for this soon, as I need node-web-audio-api for university work. Just wanted to ask if there's any reason that upgrading to speaker 0.2.5 (i.e. the current version) would cause any other unforseen issues, once I get the tests passing?

**Comment by hughrawlinson** [comment]
Oh, I have assumed that speaker is the cause of the tests failing. I'll dig into it and figure out whether or not this is the case, but if someone knows and could tell me, I'd be very grateful!

If it turns out that speaker does indeed cause test failure, would it be a good idea to make it a non-optional dependency? At the moment it's optional.

**Comment by hughrawlinson** [comment]
oh doesn't matter - this is two issues that are already registered. #33 and #34. Closing this issue.

**Comment by sebpiq** [comment]
Yeah ... I think the node-speaker dependency needs to be removed. It's really no big deal. Basically just removing it from package.json and updating the documentation to explain how to use node-web-audio-api with it. I'll see if I have time this week to do this, otherwise you can have a go.
