### ISSUE TITLE
npm package needs updating

### ISSUE THREAD

**Issue by hughrawlinson** [sebpiq/node-web-audio-api#43]
I just installed via npm and it tried to install speaker as an optional dependency. In master, speaker is not a dependency anywhere, which suggests that the npm package and master are not currently in sync.

**Comment by hughrawlinson** [comment]
Nope, was wrong - It's an optional dependency in `av`, one of our dependencies. I've submitted a PR to them to ask them to update version.

**Comment by sebpiq** [comment]
I come quite late :) 
Well done for handling this
