### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by antonharald** [sebpiq/node-web-audio-api#44]
hi guys!
I'm facing this installation issue on mac os 10.8.5 and node 4.1.2:
anyone knows what to do here?

sudo npm install web-audio-api

../deps/mpg123/src/output/coreaudio.c:14:39: warning: CoreServices/CoreServices.h: No such file or directory
../deps/mpg123/src/output/coreaudio.c:15:33: warning: AudioUnit/AudioUnit.h: No such file or directory
../deps/mpg123/src/output/coreaudio.c:16:39: warning: AudioToolbox/AudioToolbox.h: No such file or directory
../deps/mpg123/src/output/coreaudio.c:30: error: expected specifier-qualifier-list before ‘AudioConverterRef’
../deps/mpg123/src/output/coreaudio.c:51: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘playProc’
../deps/mpg123/src/output/coreaudio.c:101: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘convertProc’
../deps/mpg123/src/output/coreaudio.c: In function ‘open_coreaudio’:
../deps/mpg123/src/output/coreaudio.c:117: error: ‘UInt32’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:117: error: (Each undeclared identifier is reported only once
../deps/mpg123/src/output/coreaudio.c:117: error: for each function it appears in.)
../deps/mpg123/src/output/coreaudio.c:117: error: expected ‘;’ before ‘size’
../deps/mpg123/src/output/coreaudio.c:118: error: ‘ComponentDescription’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:118: error: expected ‘;’ before ‘desc’
../deps/mpg123/src/output/coreaudio.c:119: error: ‘Component’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:119: error: expected ‘;’ before ‘comp’
../deps/mpg123/src/output/coreaudio.c:120: error: ‘AudioStreamBasicDescription’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:120: error: expected ‘;’ before ‘inFormat’
../deps/mpg123/src/output/coreaudio.c:121: error: expected ‘;’ before ‘outFormat’
../deps/mpg123/src/output/coreaudio.c:122: error: ‘AURenderCallbackStruct’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:122: error: expected ‘;’ before ‘renderCallback’
../deps/mpg123/src/output/coreaudio.c:123: error: ‘Boolean’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:123: error: expected ‘;’ before ‘outWritable’
../deps/mpg123/src/output/coreaudio.c:126: error: ‘mpg123_coreaudio_t’ has no member named ‘play’
../deps/mpg123/src/output/coreaudio.c:127: error: ‘mpg123_coreaudio_t’ has no member named ‘buffer’
../deps/mpg123/src/output/coreaudio.c:128: error: ‘mpg123_coreaudio_t’ has no member named ‘buffer_size’
../deps/mpg123/src/output/coreaudio.c:129: error: ‘mpg123_coreaudio_t’ has no member named ‘last_buffer’
../deps/mpg123/src/output/coreaudio.c:130: error: ‘mpg123_coreaudio_t’ has no member named ‘play_done’
../deps/mpg123/src/output/coreaudio.c:131: error: ‘mpg123_coreaudio_t’ has no member named ‘decode_done’
../deps/mpg123/src/output/coreaudio.c:135: error: ‘desc’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:135: error: ‘kAudioUnitType_Output’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:136: error: ‘kAudioUnitSubType_DefaultOutput’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:137: error: ‘kAudioUnitManufacturer_Apple’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:140: error: ‘comp’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:140: warning: implicit declaration of function ‘FindNextComponent’
../deps/mpg123/src/output/coreaudio.c:146: warning: implicit declaration of function ‘OpenAComponent’
../deps/mpg123/src/output/coreaudio.c:146: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:151: warning: implicit declaration of function ‘AudioUnitInitialize’
../deps/mpg123/src/output/coreaudio.c:151: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:157: warning: implicit declaration of function ‘AudioUnitGetPropertyInfo’
../deps/mpg123/src/output/coreaudio.c:157: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:157: error: ‘kAudioUnitProperty_StreamFormat’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:157: error: ‘kAudioUnitScope_Output’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:157: error: ‘size’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:157: error: ‘outWritable’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:158: warning: implicit declaration of function ‘AudioUnitGetProperty’
../deps/mpg123/src/output/coreaudio.c:158: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:158: error: ‘outFormat’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:163: warning: implicit declaration of function ‘AudioUnitSetProperty’
../deps/mpg123/src/output/coreaudio.c:163: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:163: error: ‘kAudioUnitScope_Input’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:169: error: ‘mpg123_coreaudio_t’ has no member named ‘channels’
../deps/mpg123/src/output/coreaudio.c:170: error: ‘inFormat’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:172: error: ‘kAudioFormatLinearPCM’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:176: error: ‘kLinearPCMFormatFlagIsPacked’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:182: error: ‘kLinearPCMFormatFlagIsSignedInteger’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:183: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:187: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:190: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:194: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:197: error: ‘kLinearPCMFormatFlagIsFloat’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:198: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:202: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:203: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:205: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:208: error: ‘renderCallback’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:209: error: ‘convertProc’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:211: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:211: error: ‘kAudioUnitProperty_SetRenderCallback’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:221: warning: implicit declaration of function ‘AudioConverterNew’
../deps/mpg123/src/output/coreaudio.c:221: error: ‘mpg123_coreaudio_t’ has no member named ‘converter’
../deps/mpg123/src/output/coreaudio.c:226: error: ‘SInt32’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:226: error: expected ‘;’ before ‘channelMap’
../deps/mpg123/src/output/coreaudio.c:227: warning: implicit declaration of function ‘AudioConverterSetProperty’
../deps/mpg123/src/output/coreaudio.c:227: error: ‘mpg123_coreaudio_t’ has no member named ‘converter’
../deps/mpg123/src/output/coreaudio.c:227: error: ‘kAudioConverterChannelMap’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:227: error: ‘channelMap’ undeclared (first use in this function)
../deps/mpg123/src/output/coreaudio.c:234: error: ‘mpg123_coreaudio_t’ has no member named ‘bps’
../deps/mpg123/src/output/coreaudio.c:236: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c: In function ‘write_coreaudio’:
../deps/mpg123/src/output/coreaudio.c:253: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c:253: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c:253: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c:253: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c:258: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c:265: error: ‘mpg123_coreaudio_t’ has no member named ‘play’
../deps/mpg123/src/output/coreaudio.c:267: warning: implicit declaration of function ‘AudioOutputUnitStart’
../deps/mpg123/src/output/coreaudio.c:267: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:271: error: ‘mpg123_coreaudio_t’ has no member named ‘play’
../deps/mpg123/src/output/coreaudio.c: In function ‘close_coreaudio’:
../deps/mpg123/src/output/coreaudio.c:282: error: ‘mpg123_coreaudio_t’ has no member named ‘decode_done’
../deps/mpg123/src/output/coreaudio.c:283: error: ‘mpg123_coreaudio_t’ has no member named ‘play_done’
../deps/mpg123/src/output/coreaudio.c:283: error: ‘mpg123_coreaudio_t’ has no member named ‘play’
../deps/mpg123/src/output/coreaudio.c:286: warning: implicit declaration of function ‘AudioConverterDispose’
../deps/mpg123/src/output/coreaudio.c:286: error: ‘mpg123_coreaudio_t’ has no member named ‘converter’
../deps/mpg123/src/output/coreaudio.c:287: warning: implicit declaration of function ‘AudioOutputUnitStop’
../deps/mpg123/src/output/coreaudio.c:287: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:288: warning: implicit declaration of function ‘AudioUnitUninitialize’
../deps/mpg123/src/output/coreaudio.c:288: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:289: warning: implicit declaration of function ‘CloseComponent’
../deps/mpg123/src/output/coreaudio.c:289: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:292: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
../deps/mpg123/src/output/coreaudio.c:295: error: ‘mpg123_coreaudio_t’ has no member named ‘buffer’
../deps/mpg123/src/output/coreaudio.c:296: error: ‘mpg123_coreaudio_t’ has no member named ‘buffer’
../deps/mpg123/src/output/coreaudio.c:297: error: ‘mpg123_coreaudio_t’ has no member named ‘buffer’
../deps/mpg123/src/output/coreaudio.c: In function ‘flush_coreaudio’:
../deps/mpg123/src/output/coreaudio.c:310: error: ‘mpg123_coreaudio_t’ has no member named ‘outputUnit’
../deps/mpg123/src/output/coreaudio.c:313: error: ‘mpg123_coreaudio_t’ has no member named ‘play’
../deps/mpg123/src/output/coreaudio.c:316: error: ‘mpg123_coreaudio_t’ has no member named ‘fifo’
make: *** [Release/obj.target/output/deps/mpg123/src/output/coreaudio.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 12.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michael/node_modules/speaker
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:speaker speaker@0.0.10 install: `node-gyp rebuild`
npm WARN install:speaker Exit status 1

**Comment by codevinsky** [comment]
Make sure you're running on node 0.10.x.

```
$ npm install -g n
$ n 0.10.40

```

this will install node version 0.10.40

to switch back:

``` 
$ n
```
and select the correct version

**Comment by sebpiq** [comment]
Hey! Seems like this is the `node-speaker` dependency that fails installing. I have actually removed that dependency, and fixed this, but I forgot to publish the new version to npm. Now it is done, so you can try again, and you shouldn't have this bug anymore. However, as @codevinsky pointed out, I haven't tested this on node 4, ...
